name: Checks

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"
    - name: Install Python dependencies
      run: |
        # prerequisites
        python -m pip install --upgrade pip wheel
        python -m pip install flake8 pytest
        # install dependencies
        pip install -r requirements.txt
        # install latest version of dcoraid
        pip install git+https://github.com/DCOR-dev/DCOR-Aid.git
        # show installed packages
        pip freeze
    - name: Test with pytest
      env:
        DCOR_API_KEY: ${{ secrets.DCOR_API_KEY }}
      run: |
         py.test tests
    - name: Lint with flake8
      run: |
        flake8 --exclude _version.py .

